### ISSUE TITLE
間違ったimport

### ISSUE THREAD

**Issue by akku1139** [nakasyou/zenn-content#1]
`articles/20231020_solidjs.md`
![image](https://github.com/nakasyou/zenn-content/assets/151517253/aff3054f-2362-4814-9c48-02de1e3772ab)

`from "react"` ではなく `from "soid-js"` だと思います

**Comment by nakasyou** [comment]
ありがとうございます！
https://github.com/nakasyou/zenn-content/commit/a1b12fdde230eb478d220aaee71d17e7a7f6012a
